language: objective-c
# osx_image: xcode7.2
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
gemfile:
  - Gemfile
cache:
  directories:
  - vendor/bundle
  - vendor/Pods
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake clean
  # - pod setup > /dev/null
  - bundle exec rake pod:install > /dev/null
script:
  - bundle exec rake spec output=test_unit
# env:
#   global:
#     - COCOAPODS_NO_REPO_UPDATE_OUTPUT=true
