site_name: RedPotion
theme: readthedocs
pages:
- [index.md, Docs, Home]
- [quick_start.md, Docs, Quick start]
- [new_features_for_rmq_and_promotion.md, Docs,       "New features in RMQ and ProMotion"]
- [redpotion_specific_features.md, Docs,              "RedPotion specific features"]
- [contributing.md, Docs,                             "Contributing"]
- [cookbook/command_line.md, Cookbook,                "Command-line and REPL tools"]
- [cookbook/project.md, Cookbook,                     "Find out about the project, are you in the simulator, dev, release, on what OS, what device, etc"]
- [cookbook/device.md, Cookbook,                      "The device"]
- [cookbook/app.md, Cookbook,                         "The application and accessing it"]
- [cookbook/screens.md, Cookbook,                     "Screens"]
- [cookbook/stylesheets.md, Cookbook,                 "Using stylesheets to style and layout your screens and views"]
- [cookbook/layout_a_screen.md, Cookbook,             "Laying out a screen"]
- [cookbook/stylers.md, Cookbook,                     "Styles and stylers"]
- [cookbook/traversing.md, Cookbook,                  "Finding your way around. Traversing the app, screens, and views"]
- [cookbook/selecting.md, Cookbook,                   "Selecting or finding views"]
- [cookbook/events_and_gestures.md, Cookbook,         "Events and Gestures"]
- [cookbook/images.md, Cookbook,                      "Images, icons, and photos"]
- [cookbook/fonts.md, Cookbook,                       "Fonts"]
- [cookbook/colors.md, Cookbook,                      "Colors"]
- [cookbook/animations.md, Cookbook,                  "Animating and animations"]
- [cookbook/actions.md, Cookbook,                     "Misc actions, such as hiding, focusing, etc"]
- [cookbook/attributes.md, Cookbook,                  "Updating data or attributes"]
- [cookbook/tagging.md, Cookbook,                     "Tagging views"]
- [cookbook/core_data.md, Cookbook,                   "Using a local database"]
- [cookbook/timers.md, Cookbook,                      "Timers and delays. Do something every second"]
- [cookbook/validations.md, Cookbook,                 "Validating data, text, text boxes, etc"]
- [cookbook/format.md, Cookbook,                      "Formatting numbers and dates"]
- [cookbook/debugging.md, Cookbook,                   "Debugging"]
