site_name: RedPotion
theme: readthedocs
pages:
- [index.md, Docs, Home]
- [quick_start.md, Docs, Quick start]
- [new_features_for_rmq_and_promotion.md, Docs,       "New features in RMQ and ProMotion"]
- [redpotion_specific_features.md, Docs,              "RedPotion specific features"]
- [contributing.md, Docs,                             "Contributing"]
- [cookbook/command_line.md, Cookbook,                "Command-line and REPL tools"]
- [cookbook/project.md, Cookbook,                     "Project info, are you in the simulator, dev, release, on what OS, what device, etc"]
- [cookbook/device.md, Cookbook,                      "The device"]
- [cookbook/app_delegate.md, Cookbook,                "App delegate"]
- [cookbook/app.md, Cookbook,                         "App object: access the app from anywhere"]
- [cookbook/screens.md, Cookbook,                     "Screens: UIViewControllers"]
- [cookbook/table_screens.md, Cookbook,               "Table Screens"]
- [cookbook/stylesheets.md, Cookbook,                 "Stylesheets: style and layout your screens and views"]
- [cookbook/layout_a_screen.md, Cookbook,             "Layout: Laying out a screen"]
- [cookbook/stylers.md, Cookbook,                     "Styles and stylers"]
- [cookbook/traversing.md, Cookbook,                  "Traversing: Finding your way around screens and views"]
- [cookbook/selecting.md, Cookbook,                   "Selecting: finding views"]
- [cookbook/events_and_gestures.md, Cookbook,         "Events and Gestures"]
- [cookbook/images.md, Cookbook,                      "Images, icons, and photos"]
- [cookbook/fonts.md, Cookbook,                       "Fonts"]
- [cookbook/colors.md, Cookbook,                      "Colors"]
- [cookbook/animations.md, Cookbook,                  "Animating and animations"]
- [cookbook/actions.md, Cookbook,                     "Actions: such as hiding, focusing, etc"]
- [cookbook/attributes.md, Cookbook,                  "Attributes and data"]
- [cookbook/tagging.md, Cookbook,                     "Tagging views"]
- [cookbook/format.md, Cookbook,                      "Numbers and dates: formatting"]
- [cookbook/alerts_and_action_sheets.md, Cookbook,    "Alerts and ActionSheets"]
- [cookbook/core_data.md, Cookbook,                   "Core Data and CDQ: Using a local database"]
- [cookbook/timers.md, Cookbook,                      "Timers and delays. Do something every second"]
- [cookbook/networking.md, Cookbook,                  "Networking, JSON, remote images"]
- [cookbook/validations.md, Cookbook,                 "Validating data, text, text boxes, etc"]
- [cookbook/debugging.md, Cookbook,                   "Debugging"]
- [cookbook/testing.md, Cookbook,                     "Testing"]
- [cookbook/troubleshooting.md, Cookbook,             "Troubleshooting"]

